### ISSUE TITLE
Make set_address_window public

### ISSUE THREAD

**Issue by netthier** [sajattack/st7735-lcd-rs#16]
Hey, how do I use methods like `write_pixels` if I cant actually set the drawing window myself?
The method responsible for settings that window seems to be `set_address_window`, which isnt pub.

What I'm trying to do is draw to the screen line by line, without setting the window to that line every time.
Basically, set the window to the whole screen, draw a line, compute some stuff, draw the next line, etc.

**Comment by sajattack** [comment]
Yeah good call. Feel free to PR it and I'll merge.

**Comment by netthier** [comment]
Done :+1:
