### ISSUE TITLE
STM32F103 Blue Pill example: timers and delays

### ISSUE THREAD

**Issue by jamwaffles** [sajattack/st7735-lcd-rs#2]
As per https://github.com/jamwaffles/embedded-graphics/issues/70#issuecomment-500161644, here's an incomplete STM32F103 example. Note that this **will not compile** as the STM32F103 crate doesn't have the right timers implemented yet. It might be a good idea for compatibility to use the [`Delay` trait](https://docs.rs/embedded-hal/0.2.3/embedded_hal/blocking/delay/trait.DelayMs.html)  ([stm32f103 impl](https://docs.rs/stm32f1xx-hal/0.3.0/stm32f1xx_hal/delay/struct.Delay.html#method.delay_ms)) instead of taking up a timer.

Anyway here's the code with the `timer` arg to the driver removed:

```rust
#![no_std]
#![no_main]

extern crate cortex_m;
extern crate cortex_m_rt as rt;
extern crate panic_semihosting;
extern crate stm32f1xx_hal as hal;

use cortex_m_rt::ExceptionFrame;
use cortex_m_rt::{entry, exception};
use embedded_graphics::prelude::*;
use embedded_graphics::{image::Image16BPP, pixelcolor::PixelColorU16, primitives::Rect};
use hal::delay::Delay;
use hal::prelude::*;
use hal::spi::{Mode, Phase, Polarity, Spi};
use hal::stm32;
use st7735_lcd;
use st7735_lcd::Orientation;

#[entry]
fn main() -> ! {
    let cp = cortex_m::Peripherals::take().unwrap();
    let dp = stm32::Peripherals::take().unwrap();

    let mut flash = dp.FLASH.constrain();
    let mut rcc = dp.RCC.constrain();

    let clocks = rcc.cfgr.freeze(&mut flash.acr);

    let mut afio = dp.AFIO.constrain(&mut rcc.apb2);

    let mut gpioa = dp.GPIOA.split(&mut rcc.apb2);
    let mut gpiob = dp.GPIOB.split(&mut rcc.apb2);

    // SPI1
    let sck = gpioa.pa5.into_alternate_push_pull(&mut gpioa.crl);
    let miso = gpioa.pa6;
    let mosi = gpioa.pa7.into_alternate_push_pull(&mut gpioa.crl);

    let mut rst = gpiob.pb0.into_push_pull_output(&mut gpiob.crl);
    let dc = gpiob.pb1.into_push_pull_output(&mut gpiob.crl);

    let spi = Spi::spi1(
        dp.SPI1,
        (sck, miso, mosi),
        &mut afio.mapr,
        Mode {
            polarity: Polarity::IdleLow,
            phase: Phase::CaptureOnFirstTransition,
        },
        8.mhz(),
        clocks,
        &mut rcc.apb2,
    );

    let mut delay = Delay::new(cp.SYST, clocks);

    let mut disp = st7735_lcd::ST7735::new(spi, dc, rst, delay);
    disp.init().unwrap();
    disp.set_orientation(&Orientation::Landscape).unwrap();

    // There's a translation here because my particular lcd seems to be off a few pixels
    let black_backdrop: Rect<PixelColorU16> = Rect::new(Coord::new(0, 0), Coord::new(160, 80))
        .with_fill(Some(0x0000u16.into()))
        .translate(Coord::new(1, 25));

    disp.draw(black_backdrop.into_iter());

    let ferris =
        Image16BPP::new(include_bytes!("./ferris.raw"), 86, 64).translate(Coord::new(40, 33));

    disp.draw(ferris.into_iter());

    loop {}
}

#[exception]
fn HardFault(ef: &ExceptionFrame) -> ! {
    panic!("{:#?}", ef);
}
```

**Comment by sajattack** [comment]
Interesting. I used a timer instead of a delay because we only have delay implemented on SysTick in atsamd-hal, and using it means the end-user can't do their own delays.

**Comment by jamwaffles** [comment]
Good point on consuming SysTick. The [SSD1306](https://crates.io/crates/ssd1306), [SSD1331](https://crates.io/crates/ssd1331) and [SH1106](https://crates.io/crates/ssd1306) crates pass `delay` as an argument to their `init()` methods. That way it's free to be used by other bits of code as soon as `init()` is done. That would be a pattern to consider.

**Comment by sajattack** [comment]
Yeah, good call.

**Comment by sajattack** [comment]
Now I gotta figure out the best way to have examples targeting different architectures again.

**Comment by jamwaffles** [comment]
`[features]` might be a good way to go, even if it means typing out a `--features` flag for examples.

**Comment by sajattack** [comment]
I don't think that's possible. I meant like thumbv6m vs thumbv7em.

**Comment by jamwaffles** [comment]
I'm pretty certain feature flags would work for examples, but yeah the targets would need another flag passing in and some `.cargo/config` changes. The tradeoff is between multiple examples for multiple targets and not having to type `cargo run --example thing --features stm32f103xx --target thumbv7m` (or whatever). I'd be fine with the latter as examples for different targets would make it easier for people to get up and running with this lib. I haven't seen multiple targets for examples in other driver crates FWIW.

If I have a spare moment I'll see if I can rustle up an exploratory PR.

**Comment by sajattack** [comment]
Examples have been removed from this repo and may be added to a new repo shortly.
